name: llama
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - pip=24.2
  - python=3.10.15
  - pytorch-cuda=12.1
  - pytorch=2.1.0
  - pip:
    - accelerate==1.1.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.6.2.post1
    - async-timeout==4.0.3
    - attrs==24.2.0
    - auto-gptq==0.7.1
    - beir
    - bitsandbytes==0.44.1
    - certifi==2024.8.30
    - chardet==5.2.0
    - charset-normalizer==3.4.0
    - click==8.1.7
    - colorama==0.4.6
    - cython==3.0.11
    - dataproperty==1.0.1
    - datasets==3.1.0
    - dill==0.3.8
    - distro==1.9.0
    - dynet38==2.2
    - exceptiongroup==1.2.2
    - filelock==3.16.1
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gekko==1.2.1
    - h11==0.14.0
    - hqq
    - httpcore==1.0.6
    - httpx==0.27.2
    - huggingface-hub==0.26.2
    - idna==3.10
    - iniconfig==2.0.0
    - jieba==0.42.1
    - jinja2==3.1.4
    - jiter==0.7.0
    - jsonlines==4.0.0
    - lxml==5.3.0
    - markupsafe==3.0.2
    - mbstrdecoder==1.1.3
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - nagisa==0.2.11
    - nltk==3.9.1
    - numpy==1.26.4
    - omegaconf==2.3.0
    - openai==1.53.0
    - packaging==20.9
    - pathvalidate==3.2.1
    - peft==0.13.2
    - pluggy==1.5.0
    - portalocker==2.10.1
    - propcache==0.2.0
    - psutil==6.1.0
    - py==1.11.0
    - pyarrow==18.0.0
    - pycountry==24.6.1
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pyparsing==3.2.0
    - pytablewriter==1.2.0
    - pytest==7.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - regex==2024.9.11
    - requests==2.32.3
    - rouge==1.0.1
    - rouge-score==0.1.2
    - sacrebleu==2.4.3
    - safetensors==0.4.5
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sentencepiece==0.2.0
    - six==1.16.0
    - sniffio==1.3.1
    - sqlitedict==2.1.0
    - sympy==1.13.1
    - tabledata==1.3.3
    - tabulate==0.9.0
    - tcolorpy==0.1.6
    - termcolor==2.5.0
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - tokenizers
    - tomli==2.0.2
    - torch==2.1.0
    - tqdm==4.66.6
    - transformers==4.37.2
    - triton==2.0.0
    - typepy==1.3.2
    - typing-extensions==4.12.2
    - urllib3==2.2.3
    - xxhash==3.5.0
    - yarl==1.17.1
    - zstandard==0.23.0
    - protobuf==3.20.2
<<<<<<< HEAD
=======
    - optimum==1.23.3
>>>>>>> master
